/* Berry Action Types */
export const GET_BERRYLIST = 'GET_BERRYLIST';
export const GET_BERRYLIST_WITH_DATA = 'GET_BERRYLIST_WITH_DATA';
export const GET_BERRY = 'GET_BERRY';

/* Contest Action Types */
export const GET_CONTESTTYPELIST = 'GET_CONTESTYPETLIST';
export const GET_CONTESTTYPELIST_WITH_DATA = 'GET_CONTESTTYPELIST_WITH_DATA';
export const GET_CONTESTTYPE = 'GET_CONTESTTYPE';

export const GET_CONTESTEFFECTLIST = 'GET_CONTESTEFFECTLIST';
export const GET_CONTESTEFFECTLIST_WITH_DATA =
  'GET_CONTESTEFFECTLIST_WITH_DATA';
export const GET_CONTESTEFFECT = 'GET_CONTESTEFFECT';

export const GET_SUPERCONTESTEFFECTLIST = 'GET_SUPERCONTESTEFFECTLIST';
export const GET_SUPERCONTESTEFFECTLIST_WITH_DATA =
  'GET_SUPERCONTESTEFFECTLIST_WITH_DATA';
export const GET_SUPERCONTESTEFFECT = 'GET_SUPERCONTESTEFFECT';
